FROM chuanwen/cowsay:latest

# Teste de utilização do comando ENTRYPONT + CMD
ENTRYPOINT [ "/usr/games/cowsay" ]
CMD [ "Essa é uma imagem docker personalizada com o comando cowsay. Passe para um parametro para mudar!" ]

